version: '2'
services:
    web:
        image: nginx
        volumes:
            - "./web:/var/www/html"
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - db
    php:
        build:
            context: php5-fpm
        environment:
             - TIMEZONE='Asia/Novosibirsk'
        volumes:
            - ./web:/var/www/html
            - ./php5-fpm/conf/conf.ini:/usr/local/etc/php/conf.d/conf.ini
    composer:
        image: "composer"
        volumes:
            - "./web:/app"
        command: install
    db:
        image: mysql
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"
        volumes:
            - "./data:/var/lib/mysql"